# Default values for ui.
env: prod
appVersion: v0.1.1
# nameOverride -- A name override for resources created by the chart.
nameOverride: ""
# fullnameOverride -- A full name override for resources created by the chart.
fullnameOverride: ""

ui:
  # ui.spec.ui.image -- The image to use for ui pods.
  # @default -- `ghcr.io/ui/ui:${VERSION}`
  image:
    repository:
      dev: ''
      staging: ''
      prod: ''
   # ui.image.tag -- The tag for the ui image. Defaults to the chart version.
    tag: ''      
      # ui.spec.ui.replicas -- The number of ui replicas to run.
  replicas:
    dev: 1
    staging: 1
    prod: 1

  # ui.spec.ui.selector.matchLabels.component  -- The component label to use for ui pods.
  selector:
    matchLabels:
      component: web
  # ui.spec.ui.serviceType -- The type of service to create in front of the ui instance.
  serviceType: ClusterIP

  # ui.imagePullSecrets -- Image pull secrets for the ui pod.
  imagePullSecrets: []
  # ui.podSecurityContext -- The `PodSecurityContext` for the ui pod.
  podSecurityContext: {}
  # ui.securityContext -- The container security context for the ui pod.
  securityContext: {}
  # ui.resources -- Resource limits for the ui pod.
  resources: {}
  # ui.nodeSelector -- Node selectors for the ui pod.
  nodeSelector: {}
  # ui.tolerations -- Node tolerations for the ui pod.
  tolerations: []
  # ui.affinity -- Node affinity for the ui pod.
  affinity: {}
service:
  type: ClusterIP
  port: 3000
  targetPort: 80

