{{- $ui_api_url := index $.Values.ui.apiUrl $.Values.env }}
{{- if not $ui_api_url }}{{ fail (printf "ui_api_url info required: %s" $.Values.env) }}{{ end -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ui.fullname" . }}-config
  labels:
    {{- include "ui.labels" . | nindent 4 }}
data:
 REACT_APP_API_URL: {{ $ui_api_url | quote }}


