apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "ui.labels" . | nindent 4 }}
  name: {{ include "ui.fullname" . }}-service
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "ui.labels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
